### ISSUE TITLE
Having a placeholder and label produces overlapping text

### ISSUE THREAD

**Issue by scottcorgan** [scienceai/paper-input#2]
Example:

<img width="282" alt="screen shot 2016-03-01 at 1 14 25 pm" src="https://cloud.githubusercontent.com/assets/974723/13442117/8e135b1e-dfaf-11e5-908e-5fbf332fcf86.png">

**Comment by tiffbogich** [comment]
+1 on this issue - after using the login/signup page many times would be great to fix this one! 
![screen shot 2016-04-13 at 7 31 14 pm](https://cloud.githubusercontent.com/assets/1479502/14512577/5078a6e4-01ae-11e6-864a-8e07a3bdff33.png)

cc @callahanchris
